apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: prod
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
