apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: service-b:latest
        ports:
        - containerPort: 3001
