apiVersion: v1
kind: Service
metadata:
  name: service-a
  namespace: prod
spec:
  selector:
    app: service-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
