apiVersion: kuma.io/v1alpha1
kind: Uptime
metadata:
  name: service-a-uptime
  namespace: prod
spec:
  targetRef:
    kind: MeshService
    name: service-a
  conf:
    interval: 10s
    timeout: 2s
    unhealthyThreshold: 3
    healthyThreshold: 1
    http:
      url: http://service-a.prod.svc.cluster.local:3000/health
