apiVersion: kuma.io/v1alpha1
kind: Uptime
metadata:
  name: service-b-uptime
  namespace: stg
spec:
  targetRef:
    kind: MeshService
    name: service-b
  conf:
    interval: 10s
    timeout: 2s
    unhealthyThreshold: 3
    healthyThreshold: 1
    http:
      url: http://service-b.stg.svc.cluster.local:3000/health
